apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
spec:
  # type spécifique d'objet Service
  type: ClusterIP
  # Sélection du Deployment auquel s'applique ce ClusterIP 
  selector:
    component: redis
  # port = point d'accès pour les autres objets du cluster
  # targetPort = point d'accès pour les objets du Deployment associé (via le selector) à ce ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  